apiVersion: v1
current-context: dan-ctx
preferences: {}
clusters:
- cluster:
    certificate-authority-data: {{ ca_cert_base64 }}
    server: https://10.0.0.50:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: dan
  name: dan-ctx
kind: Config
users:
- name: dan
  user:
    client-certificate-data: {{ client_cert_base64 }}
    client-key-data: {{ client_key_base64 }}