apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ${ca_data}
      server: https://10.0.0.50:6443
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: kubernetes-admin
    name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
  - name: kubernetes-admin
    user:
      client-certificate-data: ${client_cert_data}
      client-key-data: ${client_key_data}